### ISSUE TITLE
Standardise Test-docstrings

### ISSUE THREAD

**Issue by JEThompson97** [ISISScientificComputing/autoreduce#514]
Issue raised by: [developer]

### What?
- Currently, autoreduction does not have a standard format for writing test-docstrings.
- We would like to standardise all our existing and future test-docstrings in a _Test-When_ format, example below:

> """
> Test: _create_connection() is called within connect()
> When: client._connection is None
> """

- Benefits of this standard include:
  * **Easier to write**
  * **Easier to read** and understand tests
  * **Validates testing approach** (if test behaviour doesn't match this format, suggests the test has been made incorrectly).
  * **Validates testing granularity** (if a test description can't fit neatly into this format, suggests tests need to be broken down).

- This issue is to update existing tests to this format
- It will likely need to be broken down into multiple issues due to the volume of existing tests

### Where?
All existing test-docstring (adding docstring to existing tests which do not yet have docstring is *not within scope* of this issue)
This issue will be broken down by sub-folders, as follows:
- [x] \plotting [ET] - #515 
- [ ] \paths
- [ ] \queue_processors\queue_processor\queueproc_utils
- [x] \scripts\mantid [EO] - #516
- [ ] \scripts\manual_operations
- [x] \scripts\tests\test_scheduler_ingest.py [ET] - #522
- [x] \utils\clients [ET] - #523
- [ ] \utils\data_archive
- [ ] \WebApp\autoreduce_webapp\tests\test_pagination.py

### How to test the issue is resolved
Ensure all existing tests conform to the _Test-When_ format specified above.
