### ISSUE TITLE
Remove the use of raw stomp access to AMQ

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#517]
Issue raised by: [developer]

### What?
In several places identified by @JEThompson97 we are still using raw stomp code to access activeMQ. As we move towards a harmonised system for Messages #512 it is important we also harmonise the way we access ActiveMQ. 

### Where?
The places we are using raw stomp access are:
* [x] `queue_processors/autoreduction_processor/autoreduction_processor.py` - #517 
* [x] `queue_processors/autoreduction_processor/post_process_admin.py` - #525 
* [x] `WebApp\autoreduce_webapp\autoreduce_webapp\queue_processor.py` - #538 

### How to test the issue is resolved
* Ensure all use of raw stomp connections is removed from the code base other than in the `QueueClient`.
* Ensure the functionality of each of the components above still works which should be done by:
  * Resubmitting a run from the WebApp
  * Ensuring that run successfully reaches the autoreduction processor
  * Ensure the run is successfully reduced and finishes in the completed status in the autoreduction database
* Ensure the unit tests are updated if required
