### ISSUE TITLE
Release 20.1 checklist

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#706]
Before the next version of autoreduction can be released, the following must be checked:

* [x] Inform dev team of code freeze
* [x] Create release branch 
  * [x] Update version number in setup.py AND readme front page
* [x] Identify key issues for the release
* [ ] Resolve remaining issues
* [ ] Development environment smoke test
* [ ] Production environment smoke test
* [ ] Inform customers 
* [ ] Release
