### ISSUE TITLE
Create a containerised Development Environment 

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#736]
Issue raised by: developer

### What?
Autoreductions documentation to set up a development environment can be a little tricky and time consuming to follow dependending on OS and developers background. 

Ideally, we should have a containerised development environment using docker to act as an "Autoreduction ready, out of the box environment" which developers can build and jump right into development with locally in a matter of seconds.

This containerised environment should work in conjunction with a containerised instance of the autoreduction development database #734 

It should also work with (yet to be) containerised versions of (associate github issues to each point below when made):
* ActiveMQ Service #743 
* CEPH Data Cluster (this could be a hard one to make and wouldn't blame you for leaving it out for a while) #744 
* Running Webapp service (to emulate webapp running on a separate node)

To do this you will need to make use of docker compose. 

Please remember to document your work including the following points:
* Overview of directory
* Directory contents
* Usage with examples
    * How to create, build and run the containerised environment
    * How to test everything is working as expected

You should also update documentation in the Autoreduction Wiki to reflect these changes.

When all of the above has been containerised, we will be able to use this in replacement of a development node.
We will also be able to perform end-to-end testing locally. 

### Additional notes
From exploratory research, We should be fine to use Docker for this issue.

### Where?
New Directory: autoreduction_environment/ 

### How to test the issue is resolved
* Documentation is descriptive with plenty of detail and easy to follow (ask all team members to test and critique)
* A development environment is successfully created with all system requirements
* Development environment works well with containerised databases and locally ran webapp.

### Sub-tasks
This issue can be done in separate steps as it should be possible to swap a component at a time.

- [ ] Containerised MySQL instance that has the initial DB configured so that all tests pass
  - This should be deployed on Travis
- [ ] Containerised ActiveMQ and Queue Processors that connect to the MySQL DB 
- [ ] Containerised WebApp - lowest priority as running the WebApp locally is the easiest to set up. It should also be possible to connect the local WebApp to the containers of MySQL and ActiveMQ.

**Comment by keiranjprice101** [comment]
Vagrant is not required, just nice to have. It doesn't create a dependency, as if a vagrantfile was given, it would still be optional to use and requires 0 changes to the codebase or potential containers.

**Comment by dtasev** [comment]
Done in https://github.com/ISISScientificComputing/autoreduce-containers
